<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you, your order has been placed successfully  Youll be redirected to Home page shortly</name>
   <tag></tag>
   <elementGuidId>85c35c9f-31cf-403b-9e8a-8365aea38365</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.wrapperTwo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b414acfc-3ced-424b-bc86-155ddbe27845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wrapperTwo</value>
      <webElementGuid>2e8ed1ae-31e5-40d5-b4ed-0f4c0a0e1b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you, your order has been placed successfully  You'll be redirected to Home page shortly!!</value>
      <webElementGuid>5507e593-8df5-4ff0-a0f1-99e1977bf90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;products-wrapper&quot;]/div[@class=&quot;products&quot;]/div[@class=&quot;wrapperTwo&quot;]</value>
      <webElementGuid>e7c5e67b-311b-477e-99b2-1e9f8d513b5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div</value>
      <webElementGuid>c906842d-8950-4721-85cf-cadc860dc549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KART'])[1]/following::div[3]</value>
      <webElementGuid>aae64344-5300-4e4c-a2ba-412e5f816646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[1]</value>
      <webElementGuid>a13770bf-97e6-4044-b63d-1a2bfeaa7e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>d1d6c50b-4226-418e-aa80-604e549f870e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Thank you, your order has been placed successfully  You&quot; , &quot;'&quot; , &quot;ll be redirected to Home page shortly!!&quot;) or . = concat(&quot;Thank you, your order has been placed successfully  You&quot; , &quot;'&quot; , &quot;ll be redirected to Home page shortly!!&quot;))]</value>
      <webElementGuid>0d829bc5-abf7-4ec9-b274-222fcb6e8491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
