<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DRAG ME TO MY TARGET</name>
   <tag></tag>
   <elementGuidId>a28f0250-f661-4b40-acdb-e0c74ab18be7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='draggable']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#draggable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>81816cec-3526-4169-ad74-970ed4df4a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>draggable</value>
      <webElementGuid>b2b3e237-dae2-434b-9ad5-fc02c83fc24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget-content ui-draggable ui-draggable-handle</value>
      <webElementGuid>1e7fa8c1-fa47-4f32-bc95-bfdb7d4104d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            DRAG ME TO MY TARGET!
          </value>
      <webElementGuid>79ecdd33-c8d1-4e93-aeba-8a3c41e3f4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;draggable&quot;)</value>
      <webElementGuid>42020cc3-f85f-44c5-a2e0-ca39c1ef3218</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='draggable']</value>
      <webElementGuid>50eb2656-c539-4ece-a736-0ffa546f3e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-drag-drop-thumbnail']/div</value>
      <webElementGuid>3fee6d13-16b0-4545-8f3e-5de99ef5d5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Key to Success is to take massive ACTION!'])[1]/following::div[3]</value>
      <webElementGuid>ec982bd3-db62-4fb6-a6e1-70eee193d66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WebdriverUniversity.com (Actions)'])[1]/following::div[5]</value>
      <webElementGuid>037f41e4-1e43-42bb-924b-eee7a7eed008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DROP HERE!'])[1]/preceding::div[1]</value>
      <webElementGuid>7f7c6063-414d-49ed-aa67-7492f4d2f876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>afbc08ac-8cbf-4420-893c-35342031eed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'draggable' and (text() = '
            DRAG ME TO MY TARGET!
          ' or . = '
            DRAG ME TO MY TARGET!
          ')]</value>
      <webElementGuid>03d411f2-769d-424a-8170-b70e6662b110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropped!'])[1]/preceding::div[1]</value>
      <webElementGuid>ef3057b0-6cce-45ad-b588-c2f9cbd94155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
