<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DROP HERE</name>
   <tag></tag>
   <elementGuidId>e09471c7-dd66-4631-8d9e-3d7479f75f5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='droppable']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#droppable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>86391b74-5ab9-413e-97a0-4ab89c4cf2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>droppable</value>
      <webElementGuid>e53ff94b-ad55-42db-bfdc-32c16731ef39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget-header ui-droppable</value>
      <webElementGuid>78d5e167-3d4b-4801-95e0-ca472e5a1255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            DROP HERE!
          </value>
      <webElementGuid>c539995b-9efa-4dac-a3e3-bbab1898e970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;droppable&quot;)</value>
      <webElementGuid>a1485540-9a85-4e18-9ffc-08d8fb16924c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='droppable']</value>
      <webElementGuid>e0ee8f21-c042-4bf7-8574-38adfc8b798d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-drag-drop-thumbnail']/div[2]</value>
      <webElementGuid>9dd5d61a-5f20-4460-a142-e025d9155b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DRAG ME TO MY TARGET!'])[1]/following::div[1]</value>
      <webElementGuid>d6f2348d-d9f0-45f1-8e3b-23b546d3af94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Key to Success is to take massive ACTION!'])[1]/following::div[4]</value>
      <webElementGuid>72b7e612-16dc-4a1d-91e4-bbd817772443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double Click Me!'])[1]/preceding::div[1]</value>
      <webElementGuid>81902378-a396-407f-a9a9-d568610523da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>bbb0413f-d50d-4edd-b834-e05ba46ef988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'droppable' and (text() = '
            DROP HERE!
          ' or . = '
            DROP HERE!
          ')]</value>
      <webElementGuid>e759afa8-f12f-4d5f-a85b-478874cfe53d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
